### ISSUE TITLE
Transactiondate wrong if valuta does not meet statement date.

### ISSUE THREAD

**Issue by Michamicha** [mschindler83/fints-hbci-php#16]
Hi,

currently the parser does not parse the transactiondate from rawData which leads to wrong Transactiondates, if valutadate is different from the date of the Statement.

lib/Fhp/Response/GetStatementOfAccount.php  (Line 70)

This simply sets the date to the same date as the statement, which could be terribly wrong.

Example from rawData:
Statement: 
:60F:C**160808**

Transaction:
:61:**160809**0809CR000000000001,00N033NONREF//000000
:86:082?00Test?10?20ZWECK?30xxxxxxxx?31DExxxxxxxxxxxxxxxxxxx?32Payee

Regards

Michael

**Comment by mschindler83** [comment]
Hi @Michamicha 

> currently the parser does not parse the transactiondate from rawData

As far as I know, we do parse the transaction date (booking date).
See https://github.com/mschindler83/fints-hbci-php/blob/master/lib/Fhp/Parser/MT940.php#L125-L136

For the booking date, we only take the statement date if there is no other information inside the raw data. Because it also can be that the raw data looks like this (without booking date information):

`:61:160809CR000000000001,00N033NONREF//000000`

**Comment by Michamicha** [comment]
But you already have it in code (just remarked out)

I made an adjustment that is working fine:

In lib/Fhp/parser/MT940.php change line 95 from
` //$transactionDate = $this->getDate(substr($transaction, 0, 6));`
to
` $transactionDate = $this->getDate(substr($transaction, 0, 6));`

In lib/Fhp/parser/MT940.php chenge line 119 from
` }`
to
```
$trx[count($trx) - 1]['date'] = $transactionDate;
 }
```
In lib/Fhp/Response/GetStatementOfAccount.php  replace Line 70 with :  
`$transaction->setDate(new \DateTime($trx['date']));`

transactiondate working fine...

**Comment by Michamicha** [comment]
Argh, I did not recognized the new version...
closed
