### ISSUE TITLE
Missing entries in StatementOfAccount

### ISSUE THREAD

**Issue by Soenke83** [mschindler83/fints-hbci-php#23]
These lines
            // remove not so important data
            array_shift($day);
            array_shift($day);
            array_shift($day);
            array_shift($day);
in Fhp/Parser/MT940.php can cause missing entries in StatementOfAccount.

Here a var_dump of $day before the array_shift:
array(102) {
  [0]=>
  string(90) "La?23uf?30DORTDE33XXX?31[...]?32[...]"
  [1]=>
  string(25) "61:160926C12,86NMSCNONREF"
  [2]=>
  string(134) "86:166?20EREF+NOTPROVIDED?21SVWZ+[...]?[...]?30BAWAATWWXXX?31[...]?32[...]"
  [3]=>
  string(25) "61:160926C12,98NMSCNONREF"
  [4]=>
  string(138) "86:166?20EREF+NOTPROVIDED?21SVWZ+Verwendungszweck: DFNH?2251860[...]?30SPKHDE2HXXX?31[...]?32[...]"
  [5]=>
  string(25) "61:160926C13,83NMSCNONREF"
  [6]=>
  string(149) "86:166?20EREF+SOF [...]?[...]?23alzdo rf?30WELADED1KLE?31[...]?32[...]"

$day[0], $day[1], $day[2] and $day[3] is relevant data.

I removed the lines what is working fine for me, but there probably was a reason for these lines.

**Comment by pvonauf** [comment]
Hi,
this might be an even bigger issue. I have noticed (in my case) that a line beginning with "86:" goes over two arrays. The SVWZ then goes over the last entry of the first array and the first entry of the next array. The second array also includes further transactions. The result is, that certain transactions have incomplete descriptions and as already stated by Soenke83, some transactions are missing due to the array_shift().
I'm currently trying to figure out a solotion to this ... but I'm not a PHP expert ;-)

**Comment by pvonauf** [comment]
Hey, thanks for the fix! I still however have an issue with two arrays being created accross one single transaction. This leads to an incomplete description1.
Now I found a way to solve this by replacing following line in line 59 of MT940.php

Original line:
`        $days = explode($divider . '-', $this->rawData);`

New line:
`        $days=preg_split('/([\r\n][-][\r\n]|[\r\n][-][+])/', $this->rawData);`

The old line does not work because my raw data (Deutsche Bank) looks like this sometimes (replaced some stuff):
:86:105?20EREF+LA-12431-2017-01-02-11?21-27-02-8?22MREF+N1/13002/14/2
-H?23CRED+DExxZZZxxxxxxxxxxx?24SVWZ+01.17 Autom. Sollstell?25ung 
1/3002/14/2, DG li, Stp?26l. 24 xxxxxxxxxxxx 16?27ABWA+WEG Fr
xxxxxxxxx. 16 W?30BYLADEM1001?31DE00000000000000999999?32WEG xxx
xxxxxxxxx. 16 Xxxxxx?33n

The point is the \r\n- in this case.
My new line does not consider @@ as a separator - didn't get it to work :-(
